config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "bowls#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'hall_of_fame' => 'bowls#hall_of_fame'
  get '/map' => 'restaurants#map'

  resources :bowls, only: [ :show]

  resources :restaurants, only: %i[index new create show update] do
    resources :bowls, only: %i[new create update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bowl.rb
class Bowl < ApplicationRecord
  belongs_to :restaurant
  has_many_attached :images

  def self.ransackable_attributes(auth_object = nil)
    ["restaurant_id", "review", "score", "soup", "updated_at"]
  end
end

app/models/favorite_bowl.rb
class FavoriteBowl < ApplicationRecord
  belongs_to :user
  has_many :bowls
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :bowls, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, uniqueness: true
  validates :jpn_name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/bowls_controller.rb
class BowlsController < ApplicationController
  # before_action :set_restaurant, only: %i[new create show]
  before_action :set_bowl, only: %i[new create show]
  skip_before_action :authenticate_user!, only: %i[index show hall_of_fame]
  after_action :verify_authorized, except: %i[index show hall_of_fame]
  def index
    @q = Bowl.ransack(params[:q])
    @bowls = @q.result
    policy_scope(Bowl).includes(images_attachments: :blob).all
  end

  def show
  end

  def new
    @user = current_user
    @restaurant = Restaurant.find(params[:restaurant_id])
    @bowl = Bowl.new
    authorize @bowl
  end

  def create
    @bowl = @restaurant.bowls.build(bowl_params)
    if @bowl.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def hall_of_fame
    @bowls = Bowl.all
    @top_rated = @bowls.find_all { |bowl| bowl.score == 5 }
  end

  private

  def bowl_params
    params.require(:bowl).permit(:soup, :score, :description, :review, :price, :images [])
  end

  # def set_restaurant
  #   @restaurant = Restaurant.find(params[:id])
  # end
  def set_bowl
    @bowl = Bowl.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show]
  skip_before_action :authenticate_user!, only: %i[index show map]
  after_action :verify_authorized, except: %i[index show map]

  def index
    @restaurants =
    if params[:query].present?
      policy_scope(Restaurant).where("name ILIKE ?", "%#{params[:query]}%")
    else
      policy_scope(Restaurant).includes(:bowls).all
    end
    @restaurants.each do |restaurant|
      restaurant.average_score = restaurant.bowls.average(:score).round(1) if restaurant.bowls.present?
    end
  end

  def show
    @restaurant
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    authorize @restaurant
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def map
    @restaurants = policy_scope(Restaurant)
    @markers = @restaurants.geocoded.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        info_window: render_to_string(partial: "info_window", locals: {restaurant: restaurant})
      }
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :jpn_name, :address, :average_score, :year_opened, :city, :prefecture, :station, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bowls/_bowl.haml
.bowl-card.mt-5.mb-5
  .image
    = image_tag bowl.images[0], class: "bowl-image"
  .info-container
    .px-3.d-flex.flex-column.justify-content-center.align-items-center
      %div
        = bowl.restaurant.name
      %div
        = bowl.restaurant.jpn_name

    .mt-2
      %span.material-icons-outlined.md-18.ps-2
        ramen_dining
      %span
        = bowl.soup
    %div
      %span.material-icons-outlined.md-18.ps-2 grade
      %span
        #{bowl.score}/5
    %div
      %span.material-icons-outlined.md-18.ps-2 train
      %span
        = bowl.restaurant.station
      %span.material-icons-outlined.md-18.ps-2 location_on
      %span
        = bowl.restaurant.prefecture

app/views/bowls/hall_of_fame.haml
.container
  .top-rated-container
    %h2 Hall of Fame
    - @top_rated.each do |bowl|
      = link_to bowl_path(bowl) do
        = render 'bowl', bowl: bowl

app/views/bowls/index.haml
-# = render 'layouts/search'
= search_form_for @q, url: root_path do |f|
  = f.label :soup_cont
  = f.search_field :soup_cont, placeholder: 'soup'
  = f.submit
.container.mt-3
  %h1 Recent Reviews
  .bowl-container.cards
    = @bowls.each do |bowl|
      = link_to bowl_path(bowl) do
        = render 'bowl', bowl: bowl

app/views/bowls/new.html.erb
<div class="container d-flex justify-content-center">
  <div class="w-50 p-3 d-flex flex-column justify-content-center align-items-center">
    <%= simple_form_for [@restaurant, Bowl.new] do |f| %>
      <%= f.input :soup %>
      <%= f.input :score %>
      <%= f.input :description, label: "Enter Description" %>
      <%= f.input :review, label: "Review" %>
      <%= f.input :price, label: "Price ¥" %>
      <%= f.input :images, as: :file, input_html: { multiple: true } &>
      <%= f.submit  %>
    <% end %>
  </div>
</div>

app/views/bowls/show.haml
.container
  .image-container
    = image_tag (@bowl.images[0]), class: "show-bowl"
  %h3
    = link_to restaurant_path(@bowl.restaurant) do
      = @bowl.restaurant.name
  %h5
    = @bowl.soup
  %br
  %h5 ⭐️ #{@bowl.score}
  %br
  %p
    = @bowl.review

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/dfuvnptrs/image/upload/v1675154727/ramen-ranger/ramenlogo_ycnyar.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Ramen Map", map_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Hall of Fame", hall_of_fame_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "https://cdn2.aprico-media.com/production/imgs/images/000/029/940/original.png?1553946576", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <% if current_user.admin? %>
                <%= link_to "Add Restaurant", new_restaurant_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_search.haml
.container.d-flex.justify-content-center
   = search_form_for @q do |f|
      = f.label :soup
      = f.search_field :soup
      = f.submit

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Ramen Ranger</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= favicon_link_tag asset_path('ramenlogo.png') %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%# <h1>Welcome to the Ramen Ranger!</h1>
<p>Currently residing in Osaka, but slurping bowls throughout Japan.</p>
<%= link_to "Bowls", bowls_path, class: "btn btn-primary"%> 

app/views/restaurants/_info_window.html.erb
<div class="map-popup">
  <%= link_to restaurant_path(restaurant) do %>
    <h2><%= restaurant.name %></h2>
    <p><%= restaurant.address %></p>
  <% end %>
</div>

app/views/restaurants/_map.html.erb
<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="pk.eyJ1IjoidGhpY2NyYW5nZXIiLCJhIjoiY2xjcHJ3MDMzMXBiMjNvbzV2MDU5YTVlOCJ9.ibxe-eX37nmqbkrPptFwQA"></div>

app/views/restaurants/_restaurant.html.erb
<div class="restaurant-card mt-5 mb-5">
  <div class="image">
    <% if restaurant.bowls.present? %>
      <%= image_tag (restaurant.bowls.last.images[0]), class: "bowl-image" %>
    <% else %>
    <p>no bowls</p>
    <% end %>
  </div>
  <div class="info-container">
    <div class="px-3 d-flex flex-column justify-content-center align-items-center">
      <div><%= restaurant.name %></div>
      <div><%= restaurant.jpn_name %></div>
    </div>
    <div>
      <span class="ps-2"> Avg. Score</span><span> : <%= restaurant.average_score %> / 5</span>
    </div>
    <div>
      <span class="ps-2">Times Visted</span><span> : <%= restaurant.bowls.count%></span>
    </div>
    <div class="mt-2">
      <span class="ps-2">Year Opened </span><span> : <%= restaurant.year_opened %></span>
    </div>
    <div>
      <span class="material-icons-outlined md-18 ps-2">train</span><span> : <%= restaurant.station %></span> <span class="material-icons-outlined md-18 ps-2">location_on</span><span> : <%= restaurant.prefecture %></span>
    </div>
  </div>
</div>

app/views/restaurants/index.haml
= render 'layouts/search'
.container
  %h1 Restaurants Page
  .bowl-container.cards
    - @restaurants.each do |restaurant|
      = link_to restaurant_path(restaurant) do
        = render 'restaurant', restaurant: restaurant

app/views/restaurants/map.html.erb
<div class="container">
  <%= render 'map' %>
</div>

app/views/restaurants/new.html.erb
<div class="container d-flex justify-content-center">
  <div class="w-50 p-3 d-flex flex-column justify-content-center align-items-center">
    <%= simple_form_for(@restaurant) do |f| %>
      <%= f.input :name %>
      <%= f.input :jpn_name %>
      <%= f.input :latitude %>
      <%= f.input :longitude %>
      <%= f.input :address %>
      <%= f.input :year_opened %>
      <%= f.input :city, label: "Location (city)" %>
      <%= f.input :prefecture %>
      <%= f.input :station %>
      <%= f.input :photo, as: :file %>
      <%= f.submit  %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h3><%= @restaurant.name %></h3>
  <h3><%= @restaurant.address %></h3>
  <% if policy(@restaurant).new? %>
    <%= link_to 'Add a bowl', new_restaurant_bowl_path(@restaurant, @bowl) %>
  <% end %>
  <div class="cards">
    <% @restaurant.bowls.reverse_each do |bowl| %>
      <%= link_to bowl_path(bowl) do %>
        <%= render 'bowls/bowl', bowl: bowl  %>
      <% end %>
    <% end %>
  </div>
</div>